# Generated by Django 5.2.3 on 2025-06-21 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/', verbose_name='프로필 이미지')),
                ('is_social_account', models.BooleanField(default=False, verbose_name='소셜 계정 여부')),
                ('social_provider', models.CharField(blank=True, max_length=20, verbose_name='소셜 제공자')),
                ('terms_agreed', models.BooleanField(default=False, verbose_name='이용약관 동의')),
                ('privacy_agreed', models.BooleanField(default=False, verbose_name='개인정보처리방침 동의')),
                ('marketing_agreed', models.BooleanField(default=False, verbose_name='마케팅 수신 동의')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필들',
                'ordering': ['-created_at'],
            },
        ),
    ]
