# Generated by Django 5.2.3 on 2025-06-21 22:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('specialty', models.CharField(choices=[('civil', '민사법'), ('criminal', '형사법'), ('family', '가족법'), ('corporate', '기업법'), ('tax', '세무법'), ('labor', '노동법'), ('real_estate', '부동산법'), ('intellectual_property', '지적재산권법'), ('medical', '의료법'), ('environmental', '환경법')], max_length=50, verbose_name='전문분야')),
                ('experience_years', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='경력년수')),
                ('description', models.TextField(verbose_name='소개')),
                ('hourly_rate', models.IntegerField(verbose_name='시간당 상담료')),
                ('profile_image', models.URLField(blank=True, verbose_name='프로필 이미지')),
                ('office_address', models.CharField(max_length=200, verbose_name='사무실 주소')),
                ('phone', models.CharField(max_length=15, verbose_name='전화번호')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2, verbose_name='평점')),
                ('review_count', models.IntegerField(default=0, verbose_name='리뷰 수')),
                ('university', models.CharField(max_length=100, verbose_name='출신대학')),
                ('career_highlights', models.TextField(blank=True, verbose_name='주요 경력')),
                ('consultation_count', models.IntegerField(default=0, verbose_name='상담 건수')),
                ('success_rate', models.IntegerField(default=85, verbose_name='승률')),
            ],
            options={
                'verbose_name': '변호사',
                'verbose_name_plural': '변호사들',
            },
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '월요일'), (1, '화요일'), (2, '수요일'), (3, '목요일'), (4, '금요일'), (5, '토요일'), (6, '일요일')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='lawyers.lawyer')),
            ],
            options={
                'verbose_name': '상담 가능 시간',
                'verbose_name_plural': '상담 가능 시간들',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, verbose_name='의뢰인')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='평점')),
                ('comment', models.TextField(verbose_name='리뷰 내용')),
                ('case_type', models.CharField(max_length=50, verbose_name='사건 유형')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lawyers.lawyer')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰들',
                'ordering': ['-created_at'],
            },
        ),
    ]
